'use client';                                                                                                                                                                                                                                   

 import { createConfig, http } from 'wagmi';                                                                                                                                                                                                     
 import { base } from 'wagmi/chains';                                                                                                                                                                                                            
 import { createPublicClient, createWalletClient, custom } from 'viem';                                                                                                                                                                          
 import { metaMask } from 'wagmi/connectors';                                                                                                                                                                                                    

 // Base Mainnet Config (8453) — NO THIRDWEB, VIEM ONLY                                                                                                                                                                                          
 export const config = createConfig({                                                                                                                                                                                                            
   chains: [base],                                                                                                                                                                                                                               
   transports: {                                                                                                                                                                                                                                 
     [base.id]: http('https://mainnet.base.org') ,                                                                                                                                                                                               
   },                                                                                                                                                                                                                                            
   connectors: [metaMask()],                                                                                                                                                                                                                     
 });                                                                                                                                                                                                                                             

 export const publicClient = createPublicClient({                                                                                                                                                                                                
   chain: base,                                                                                                                                                                                                                                  
   transport: http('https://mainnet.base.org') ,                                                                                                                                                                                                 
 });                                                                                                                                                                                                                                             

 export const walletClient = createWalletClient({                                                                                                                                                                                                
   chain: base,                                                                                                                                                                                                                                  
   transport: custom(window.ethereum), // MetaMask                                                                                                                                                                                               
 });                                                                                                                                                                                                                                             

 // Contract                                                                                                                                                                                                                                     
 export const contractAddress = '0x65d7245Ab1F2382a6F9fb0e1f14be 8cdf1Bb4A69'; // Mainnet LIVE                                                                                                                                                   

 // ABI for mintTo (standard NFT — adjust if custom)                                                                                                                                                                                             
 export const contractABI = [                                                                                                                                                                                                                    
   {                                                                                                                                                                                                                                             
     "inputs": [                                                                                                                                                                                                                                 
       {"name": "to", "type": "address"},                                                                                                                                                                                                        
       {"name": "uri", "type": "string"},                                                                                                                                                                                                        
       {"name": "value", "type": "string"},                                                                                                                                                                                                      
       {"name": "signature", "type": "bytes"},                                                                                                                                                                                                   
       {"name": "timestamp", "type": "uint256"}                                                                                                                                                                                                  
     ],                                                                                                                                                                                                                                          
     "name": "mintTo",                                                                                                                                                                                                                           
     "outputs": [],                                                                                                                                                                                                                              
     "stateMutability": "nonpayable",                                                                                                                                                                                                            
     "type": "function"                                                                                                                                                                                                                          
   }                                                                                                                                                                                                                                             
 ] as const;                                                                                                                                                                                                                                     

 console.log('[BASE MAINNET VIEM] Config loaded for chain 8453, contract', contractAddress);                                                                                                                                                     

 QCForm.tsx                                                                                                                                                                                                                                      
 'use client';                                                                                                                                                                                                                                   

 import { useState } from 'react';                                                                                                                                                                                                               
 import { useAccount, useConnect, useWalletClient } from 'wagmi';                                                                                                                                                                                
 import { metaMask } from 'wagmi/connectors';                                                                                                                                                                                                    
 import { createWalletClient, custom, parseAbi, encodeFunctionData } from 'viem';                                                                                                                                                                
 import { base } from 'wagmi/chains';                                                                                                                                                                                                            
 import { config, contractAddress, contractABI, publicClient } from '../app/client';                                                                                                                                                             

 interface MeasurementData {                                                                                                                                                                                                                     
   hash: string;                                                                                                                                                                                                                                 
   timestamp: number;                                                                                                                                                                                                                            
   value: string;                                                                                                                                                                                                                                
   metadataUri: string;                                                                                                                                                                                                                          
 }                                                                                                                                                                                                                                               

 export default function QCForm() {                                                                                                                                                                                                              
   const { address, isConnected } = useAccount();                                                                                                                                                                                                
   const { connect } = useConnect();                                                                                                                                                                                                             
   const { data: walletClient } = useWalletClient({ config });                                                                                                                                                                                   
   const [data, setData] = useState<MeasurementData>({                                                                                                                                                                                           
     hash: '',                                                                                                                                                                                                                                   
     timestamp: Date.now(),                                                                                                                                                                                                                      
     value: '',                                                                                                                                                                                                                                  
     metadataUri: ''                                                                                                                                                                                                                             
   });                                                                                                                                                                                                                                           
   const [error, setError] = useState('');                                                                                                                                                                                                       
   const [loading, setLoading] = useState(false);                                                                                                                                                                                                
   const [txnHash, setTxnHash] = useState('');                                                                                                                                                                                                   

   const headerTitle = 'FDA-Grade Integrity on Base Mainnet'; // Base Mainnet                                                                                                                                                                    

   const handleQCCommit = async () => {                                                                                                                                                                                                          
     if (!isConnected || !address) {                                                                                                                                                                                                             
       setError('Connect MetaMask to Base Mainnet first');                                                                                                                                                                                       
       return;                                                                                                                                                                                                                                   
     }                                                                                                                                                                                                                                           
     if (!data.hash || !data.value) {                                                                                                                                                                                                            
       setError('Fill form');                                                                                                                                                                                                                    
       return;                                                                                                                                                                                                                                   
     }                                                                                                                                                                                                                                           

 ```                                                                                                                                                                                                                                             
   setLoading(true);                                                                                                                                                                                                                             
   setError('');                                                                                                                                                                                                                                 

   try {                                                                                                                                                                                                                                         
     console.log('[BASE MAINNET VIEM] Starting direct mintTo on 8453');                                                                                                                                                                          

     // Sign payload                                                                                                                                                                                                                             
     const payload = { ...data, signer: address, chainId: 8453 };                                                                                                                                                                                
     const signature = await walletClient?.signMessage({ message: JSON.stringify(payload) });                                                                                                                                                    
     if (!signature) throw new Error('Signing failed');                                                                                                                                                                                          
     console.log('[BASE MAINNET VIEM] Signed:', signature.slice(0, 10) + '...');                                                                                                                                                                 

     // Balance check                                                                                                                                                                                                                            
     const balance = await publicClient.getBalance({ address });                                                                                                                                                                                 
     const eth = Number(balance) / 1e18;                                                                                                                                                                                                         
     console.log('[BASE MAINNET VIEM] Balance:', eth, 'ETH');                                                                                                                                                                                    
     if (eth < 0.001) throw new Error('Bridge ETH to Base Mainnet');                                                                                                                                                                             

     const uri = data.metadataUri || `ipfs://QmMainnet${data.hash.sli ce(0, 8)}`;                                                                                                                                                                

     // Encode mintTo call                                                                                                                                                                                                                       
     const { request } = await publicClient.simulateContract({                                                                                                                                                                                   
       address: contractAddress,                                                                                                                                                                                                                 
       abi: contractABI,                                                                                                                                                                                                                         
       functionName: 'mintTo',                                                                                                                                                                                                                   
       args: [address, uri, data.value, signature, BigInt(data.timestamp)],                                                                                                                                                                      
       account: address,                                                                                                                                                                                                                         
     });                                                                                                                                                                                                                                         

     // Send direct txn (EOA, no paymaster)                                                                                                                                                                                                      
     console.log('[BASE MAINNET VIEM] Sending direct EOA txn');                                                                                                                                                                                  
     const hash = await walletClient?.sendTransaction(re quest);                                                                                                                                                                                 
     if (!hash) throw new Error('Txn send failed');                                                                                                                                                                                              
     setTxnHash(hash);                                                                                                                                                                                                                           
     console.log('[BASE MAINNET VIEM SUCCESS] Txn hash:', hash);                                                                                                                                                                                 
     alert(`QC on Base Mainnet! https://basescan.org/tx/${hash}` );                                                                                                                                                                              

     console.log(`[AUDIT] Mainnet mint: ${new Date().toISOString()}, Hash: ${data.hash}`);                                                                                                                                                       
   } catch (err: any) {                                                                                                                                                                                                                          
     const msg = err.message || 'Direct mint failed';                                                                                                                                                                                            
     console.error('[BASE MAINNET VIEM ERROR]', err);                                                                                                                                                                                            
     setError(`Base Mainnet Error: ${msg}`);                                                                                                                                                                                                     
   } finally {                                                                                                                                                                                                                                   
     setLoading(false);                                                                                                                                                                                                                          
   }                                                                                                                                                                                                                                             
 ```                                                                                                                                                                                                                                             

   };                                                                                                                                                                                                                                            

   const viewTxn = () => txnHash && window.open(`https://basescan.org/tx/${txnHash}`, '_blank');                                                                                                                                                  

   return (                                                                                                                                                                                                                                      
     <div style={{ maxWidth: '400px', margin: 'auto', padding: '20px' }}>                                                                                                                                                                        
       <h2>{headerTitle}</h2>                                                                                                                                                                                                                    
       <p>Mint QC NFT on Base Mainnet (8453) — Direct EOA Mode.</p>                                                                                                                                                                              
       {!isConnected ? (                                                                                                                                                                                                                         
         <button onClick={() => connect({ connector: metaMask() })} style={{ padding: '10px', background: '#0070f3', color: 'white', border: 'none' }}>                                                                                          
           Connect MetaMask to Base Mainnet                                                                                                                                                                                                      
         </button>                                                                                                                                                                                                                               
       ) : (                                                                                                                                                                                                                                     
         <form onSubmit={(e) => { e.preventDefault(); handleQCCommit(); }}>                                                                                                                                                                      
           <input                                                                                                                                                                                                                                
             type="text"                                                                                                                                                                                                                         
             placeholder="Data Hash"                                                                                                                                                                                                             
             value={data.hash}                                                                                                                                                                                                                   
             onChange={(e) => setData({ ...data, hash: e.target.value })}                                                                                                                                                                        
             required                                                                                                                                                                                                                            
             disabled={loading}                                                                                                                                                                                                                  
             style={{ width: '100%', marginBottom: '10px', padding: '8px' }}                                                                                                                                                                     
           />                                                                                                                                                                                                                                    
           <input                                                                                                                                                                                                                                
             type="text"                                                                                                                                                                                                                         
             placeholder="Value (e.g., 7.2)"                                                                                                                                                                                                     
             value={data.value}                                                                                                                                                                                                                  
             onChange={(e) => setData({ ...data, value: e.target.value })}                                                                                                                                                                       
             required                                                                                                                                                                                                                            
             disabled={loading}                                                                                                                                                                                                                  
             style={{ width: '100%', marginBottom: '10px', padding: '8px' }}                                                                                                                                                                     
           />                                                                                                                                                                                                                                    
           <input                                                                                                                                                                                                                                
             type="text"                                                                                                                                                                                                                         
             placeholder="IPFS URI (optional)"                                                                                                                                                                                                   
             value={data.metadataUri}                                                                                                                                                                                                            
             onChange={(e) => setData({ ...data, metadataUri: e.target.value })}                                                                                                                                                                 
             disabled={loading}                                                                                                                                                                                                                  
             style={{ width: '100%', marginBottom: '10px', padding: '8px' }}                                                                                                                                                                     
           />                                                                                                                                                                                                                                    
           <button                                                                                                                                                                                                                               
             type="submit"                                                                                                                                                                                                                       
             disabled={loading || !data.hash || !data.value}                                                                                                                                                                                     
             style={{ width: '100%', padding: '10px', background: '#0070f3', color: 'white', border: 'none' }}                                                                                                                                   
           >                                                                                                                                                                                                                                     
             {loading ? 'Minting on Mainnet...' : 'Sign & Submit to Base Mainnet (EOA)'}                                                                                                                                                         
           </button>                                                                                                                                                                                                                             
           {error && <p style={{ color: 'red', marginTop: '10px' }}>{error}</p>}                                                                                                                                                                 
           {txnHash && (                                                                                                                                                                                                                         
             <div style={{ marginTop: '10px' }}>                                                                                                                                                                                                 
               <p>Mainnet Txn: {txnHash.slice(0, 20)}...</p>                                                                                                                                                                                     
               <button onClick={viewTxn} style={{ padding: '5px 10px' }}>Basescan</button>                                                                                                                                                       
             </div>                                                                                                                                                                                                                              
           )}                                                                                                                                                                                                                                    
           <p style={{ fontSize: '0.8em', marginTop: '20px' }}>                                                                                                                                                                                  
             <em>Direct to 0x65d7245Ab1F2382a6F9fb0e1f14be8 cdf1Bb4A69 on Base Mainnet — No SDK</em>                                                                                                                                             
           </p>                                                                                                                                                                                                                                  
         </form>                                                                                                                                                                                                                                 
       )}                                                                                                                                                                                                                                        
     </div>                                                                                                                                                                                                                                      
   );                                                                                                                                                                                                                                            
 }                                                                                                                                                                                                                                               
